name: Feature Suggestion
description: Propose a change or addition.
title: "[Feature Proposal]: "
labels: [feature-suggestion]
body:
  - type: markdown
    attributes:
      value: |
        We welcome feature proposals! We have a process to evaluate the value and shape of new API. This template will help us gather the information we need to start the review process.
  - type: textarea
    id: background
    attributes:
      label: Background and motivation
      description: Please describe the purpose and value of the new feature here.
      placeholder: Purpose
    validations:
      required: true
  - type: textarea
    id: feature-proposal
    attributes:
      label: Feature Proposal
      description: |
        Please provide the specific public API signature or the modification that you are proposing.
      placeholder: API declaration (no method bodies)
      value: |
        ```csharp
        namespace System.Collections.Generic;

        public class MyFancyCollection<T> : IEnumerable<T>
        {
            public void Fancy(T item);
        }
        ```
    validations:
      required: true
  - type: textarea
    id: api-usage
    attributes:
      label: API Usage
      description: |
        Please provide code examples that highlight how the proposed API additions are meant to be consumed. This will help suggest whether the API has the right shape to be functional, performant and usable.
      placeholder: API usage
      value: |
        ```csharp
        // Fancy the value
        var c = new MyFancyCollection<int>();
        c.Fancy(42);

        // Getting the values out
        foreach (var v in c)
            Console.WriteLine(v);
        ```
    validations:
      required: true
  - type: textarea
    id: other-notes
    attributes:
      label: Other Notes
      description: |
        Do you have any other thoughts or concerns? This is also a good place for noting any risks, such as breaking changes or performance regressions, or describing edge case situations.
      placeholder: Several people are typing...
    validations:
      required: false
